export const LIKE_PET = "LIKE_PET";
export const DELETE_PET = "DELETE_PET";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
// export const UPDATE_PET = 'UPDATE_PET';
export const FILTER_PETS = "FILTER_PETS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
